name = "tight-wave-a6ed"
main = "whatsapp-goal-worker.js"
compatibility_date = "2026-07-16"

[[kv_namespaces]]
binding = "SELIN_MEMORY"
id = "c9e07497d728460da708feaa9148190e"

[[kv_namespaces]]
binding = "SOPHIE_MEMORY"
id = "1ca656309cb44ec8b8852a3a1d46e9d0"

[ai]
binding = "AI"
